services:
  compteur-de-visiteurs:
    container_name: compteur-social-dev
    build:
      context: .
      dockerfile: node.dev.Dockerfile
    stdin_open: true
    tty: true
    working_dir: /home/node/app
    ports:
      - 3900:3900
      - 5173:5173
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max_old_space_size=2048
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
  mailer:
    image: axllent/mailpit
    container_name: mailpit
    ports:
        - 1025:1025
        - 8025:8025
    environment:
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
        MAILPIT_RELAY: 127.0.0.1:25

volumes:
  node_modules:
