services:
  compteur-de-visiteurs:
    container_name: compteur-social-dev
    build:
      context: .
      target: dev
    ports:
      - "${PORT}:${PORT}"
      - 5173:5173
      - 24678:24678
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max_old_space_size=2048
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "
        npm run database:dev &&
        npm run dev
      "
    networks:
      - compteur-social-network
  mailer:
    image: axllent/mailpit
    container_name: compteur-social-mailpit
    ports:
        - 1025:1025
        - 8025:8025
    environment:
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
        MAILPIT_RELAY: 127.0.0.1:25

volumes:
  node_modules:

networks:
  compteur-social-network:
    driver: bridge