version: "3.9"

services:
  init-tmp:
    image: busybox
    container_name: init-tmp
    command: ["sh", "-c", "mkdir -p /host/tmp && chmod 777 /host/tmp"]
    volumes:
      - ./tmp:/host/tmp
    # This service exits immediately after creating the folder
    restart: "no"

  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - --api.insecure=true                   # enable dashboard
      - --providers.docker=true               # use Docker as provider
      - --entrypoints.web.address=:80         # HTTP entrypoint
    ports:
      - 80:80                             # HTTP
      - 8080:8080                           # Dashboard
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    restart: unless-stopped

  compteur-de-visiteurs:
    container_name: compteur-social-production
    build:
      context: .
      dockerfile: node.Dockerfile
    volumes:
      - ./whitelist-ip.tmp.txt:/app/whitelist-ip.tmp.txt
      - ./database-docker.tmp.sqlite:/app/database-prod.tmp.sqlite
    depends_on:
      - init-tmp
    stdin_open: true
    tty: true
    ports:
      - 3900:3900
    environment:
      - NODE_ENV=production
      - IS_DOCKER=true
    env_file:
      - .env.local
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.compteur.rule=Host("faclab.localhost")'
      - 'traefik.http.routers.compteur.entrypoints=web'
    restart: unless-stopped
